"""
Report Generator for VulnHunter
Generates professional HackerOne-style vulnerability reports
"""

import json
from typing import Optional, Dict, List, Any
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from loguru import logger


@dataclass
class VulnerabilityReport:
    """A complete vulnerability report"""
    id: str
    title: str
    severity: str  # critical, high, medium, low, info
    cvss_score: float = 0.0
    cwe_id: str = ""
    
    # Summary
    summary: str = ""
    
    # Technical Details
    vulnerability_type: str = ""
    affected_url: str = ""
    affected_parameter: str = ""
    http_method: str = ""
    
    # Reproduction
    steps_to_reproduce: List[str] = field(default_factory=list)
    payload: str = ""
    
    # Evidence
    request: str = ""
    response: str = ""
    screenshot: str = ""
    
    # Impact
    impact: str = ""
    attack_scenario: str = ""
    
    # Remediation
    remediation: str = ""
    references: List[str] = field(default_factory=list)
    
    # Metadata
    discovered_at: datetime = field(default_factory=datetime.now)
    confidence: str = "medium"
    
    def to_dict(self) -> Dict:
        return {
            'id': self.id,
            'title': self.title,
            'severity': self.severity,
            'cvss_score': self.cvss_score,
            'cwe_id': self.cwe_id,
            'summary': self.summary,
            'vulnerability_type': self.vulnerability_type,
            'affected_url': self.affected_url,
            'affected_parameter': self.affected_parameter,
            'steps_to_reproduce': self.steps_to_reproduce,
            'payload': self.payload,
            'impact': self.impact,
            'remediation': self.remediation,
            'references': self.references,
            'discovered_at': self.discovered_at.isoformat(),
        }
    
    def to_markdown(self) -> str:
        """Generate HackerOne-style markdown report"""
        
        severity_badge = {
            'critical': '🔴 CRITICAL',
            'high': '🟠 HIGH',
            'medium': '🟡 MEDIUM',
            'low': '🟢 LOW',
            'info': '⚪ INFO',
        }.get(self.severity.lower(), self.severity.upper())
        
        md = f"""# {self.title}

**Severity:** {severity_badge}
**CVSS Score:** {self.cvss_score}
**CWE:** {self.cwe_id}
**Vulnerability Type:** {self.vulnerability_type}

---

## Summary

{self.summary}

## Affected Component

- **URL:** `{self.affected_url}`
- **Parameter:** `{self.affected_parameter}`
- **HTTP Method:** {self.http_method}

## Steps to Reproduce

"""
        for i, step in enumerate(self.steps_to_reproduce, 1):
            md += f"{i}. {step}\n"
        
        md += f"""
## Payload

```
{self.payload}
```

## Proof of Concept

### Request
```http
{self.request}
```

### Response
```http
{self.response[:2000]}
```

## Impact

{self.impact}

### Attack Scenario

{self.attack_scenario}

## Remediation

{self.remediation}

## References

"""
        for ref in self.references:
            md += f"- {ref}\n"
        
        md += f"""
---

*Report generated by VulnHunter on {self.discovered_at.strftime('%Y-%m-%d %H:%M:%S')}*
"""
        return md
    
    def to_hackerone_format(self) -> str:
        """Generate report in HackerOne submission format"""
        
        return f"""## Summary
{self.summary}

## Vulnerability Type
{self.vulnerability_type} ({self.cwe_id})

## Steps To Reproduce
{''.join([f"{i}. {step}" + chr(10) for i, step in enumerate(self.steps_to_reproduce, 1)])}

## Supporting Material/References
- Affected URL: {self.affected_url}
- Parameter: {self.affected_parameter}
- Payload: `{self.payload}`

## Impact
{self.impact}

{self.attack_scenario}

## Suggested Remediation
{self.remediation}
"""


class ReportGenerator:
    """
    Generates professional vulnerability reports
    """
    
    def __init__(self, output_dir: str = "./reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        
        self.reports: List[VulnerabilityReport] = []
        
        # CWE mappings
        self.cwe_mappings = {
            'sqli': 'CWE-89: SQL Injection',
            'xss': 'CWE-79: Cross-site Scripting',
            'xss-dom': 'CWE-79: Cross-site Scripting (DOM-based)',
            'csrf': 'CWE-352: Cross-Site Request Forgery',
            'idor': 'CWE-639: Authorization Bypass Through User-Controlled Key',
            'ssrf': 'CWE-918: Server-Side Request Forgery',
            'lfi': 'CWE-22: Path Traversal',
            'rce': 'CWE-78: OS Command Injection',
            'auth': 'CWE-287: Improper Authentication',
            'info': 'CWE-200: Information Exposure',
            'ssti': 'CWE-94: Code Injection',
        }
        
        # CVSS base scores
        self.severity_cvss = {
            'critical': 9.5,
            'high': 7.5,
            'medium': 5.5,
            'low': 3.0,
            'info': 0.0,
        }
        
        # Remediation templates
        self.remediation_templates = {
            'sqli': """1. Use parameterized queries (prepared statements) for all database operations
2. Implement input validation with allowlisting
3. Apply principle of least privilege to database accounts
4. Use an ORM that handles query parameterization
5. Enable WAF rules for SQL injection protection""",
            
            'xss': """1. Encode all output based on context (HTML, JavaScript, URL, CSS)
2. Implement Content-Security-Policy headers
3. Use HTTPOnly and Secure flags on session cookies
4. Validate and sanitize user input
5. Use modern frameworks with automatic escaping""",
            
            'idor': """1. Implement proper authorization checks before accessing resources
2. Use indirect object references (mapping)
3. Validate that the authenticated user owns the requested resource
4. Log and monitor access to sensitive resources
5. Consider implementing access control lists (ACL)""",
            
            'ssrf': """1. Validate and sanitize all user-supplied URLs
2. Use allowlisting for permitted domains/IPs
3. Block requests to internal networks (RFC 1918)
4. Disable unnecessary URL schemes (file://, gopher://, etc.)
5. Use network-level controls to restrict outbound requests""",
            
            'auth': """1. Implement account lockout after failed attempts
2. Use strong password policies
3. Implement multi-factor authentication
4. Use secure session management
5. Remove or change default credentials""",
        }
        
        # Impact templates
        self.impact_templates = {
            'sqli': """An attacker could exploit this SQL injection vulnerability to:
- Extract sensitive data from the database (user credentials, personal information, financial data)
- Modify or delete data in the database
- Bypass authentication mechanisms
- Potentially gain command execution on the database server
- Escalate privileges within the application""",
            
            'xss': """An attacker could exploit this XSS vulnerability to:
- Steal user session cookies and hijack accounts
- Perform actions on behalf of authenticated users
- Redirect users to malicious websites
- Deface the web application
- Distribute malware to users
- Steal sensitive information entered by users""",
            
            'idor': """An attacker could exploit this IDOR vulnerability to:
- Access other users' personal data and accounts
- View confidential documents or resources
- Modify other users' data or settings
- Delete resources belonging to other users
- Escalate privileges to admin accounts""",
            
            'ssrf': """An attacker could exploit this SSRF vulnerability to:
- Access internal services and infrastructure
- Retrieve cloud metadata credentials (AWS/GCP/Azure)
- Scan internal network services
- Bypass firewall protections
- Potentially achieve remote code execution on internal systems""",
        }
    
    def create_report_from_finding(self, finding: Dict) -> VulnerabilityReport:
        """
        Create a full report from a vulnerability finding
        
        LLM Usage:
            report = generator.create_report_from_finding(finding_dict)
        """
        category = finding.get('category', 'unknown')
        severity = finding.get('severity', 'medium')
        
        # Get CWE
        cwe = finding.get('cwe_id', '') or self.cwe_mappings.get(category, '')
        
        # Get CVSS
        cvss = finding.get('cvss_score', 0) or self.severity_cvss.get(severity, 5.0)
        
        # Generate steps to reproduce
        steps = [
            f"Navigate to: {finding.get('url', 'N/A')}",
            f"Locate the '{finding.get('parameter', 'input')}' parameter",
            f"Insert the payload: {finding.get('payload', 'N/A')}",
            "Submit the request",
            f"Observe the {finding.get('evidence', 'vulnerability indicator')}",
        ]
        
        # Get impact and remediation
        impact = self.impact_templates.get(category, finding.get('description', ''))
        remediation = self.remediation_templates.get(
            category, 
            finding.get('remediation', 'Implement proper security controls.')
        )
        
        report = VulnerabilityReport(
            id=finding.get('id', self._generate_id()),
            title=finding.get('title', f'{category.upper()} Vulnerability'),
            severity=severity,
            cvss_score=cvss,
            cwe_id=cwe,
            summary=finding.get('description', ''),
            vulnerability_type=category.upper(),
            affected_url=finding.get('url', ''),
            affected_parameter=finding.get('parameter', ''),
            http_method=finding.get('method', 'GET'),
            steps_to_reproduce=steps,
            payload=finding.get('payload', ''),
            request=finding.get('request', ''),
            response=finding.get('response', '')[:1000],
            impact=impact,
            attack_scenario=self._generate_attack_scenario(category, finding),
            remediation=remediation,
            references=self._get_references(category),
            confidence=finding.get('confidence', 'medium'),
        )
        
        self.reports.append(report)
        return report
    
    def _generate_id(self) -> str:
        """Generate unique report ID"""
        import hashlib
        return hashlib.md5(str(datetime.now()).encode()).hexdigest()[:12]
    
    def _generate_attack_scenario(self, category: str, finding: Dict) -> str:
        """Generate realistic attack scenario"""
        scenarios = {
            'sqli': f"""
**Attack Scenario:**
1. Attacker discovers the vulnerable parameter `{finding.get('parameter', 'input')}` at `{finding.get('url', 'the endpoint')}`
2. Using tools like sqlmap, attacker extracts database schema
3. Attacker dumps user table containing emails, passwords, and personal data
4. Attacker uses stolen credentials to access user accounts
5. If database user has file privileges, attacker could read server files or execute commands
""",
            'xss': f"""
**Attack Scenario:**
1. Attacker crafts a malicious URL containing the XSS payload
2. Attacker sends the link to victims via phishing email or social media
3. When victim clicks the link, the JavaScript executes in their browser
4. The script steals the victim's session cookie and sends it to attacker's server
5. Attacker uses the stolen session to impersonate the victim
""",
            'idor': f"""
**Attack Scenario:**
1. Attacker creates a legitimate account on the application
2. Attacker notices numeric ID `{finding.get('parameter', 'id')}` in requests
3. Attacker iterates through ID values to access other users' data
4. Attacker extracts sensitive information from multiple accounts
5. Attacker could modify or delete other users' resources
""",
            'ssrf': f"""
**Attack Scenario:**
1. Attacker identifies the URL parameter `{finding.get('parameter', 'url')}`
2. Attacker submits internal IP addresses to probe internal network
3. Attacker discovers cloud metadata endpoint (169.254.169.254)
4. Attacker extracts AWS/GCP/Azure credentials from metadata
5. Attacker uses credentials to access cloud resources and escalate privileges
""",
        }
        return scenarios.get(category, "Attacker could exploit this vulnerability to compromise the application.")
    
    def _get_references(self, category: str) -> List[str]:
        """Get reference links for vulnerability type"""
        refs = {
            'sqli': [
                "https://owasp.org/www-community/attacks/SQL_Injection",
                "https://portswigger.net/web-security/sql-injection",
                "https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html",
            ],
            'xss': [
                "https://owasp.org/www-community/attacks/xss/",
                "https://portswigger.net/web-security/cross-site-scripting",
                "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html",
            ],
            'idor': [
                "https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/05-Authorization_Testing/04-Testing_for_Insecure_Direct_Object_References",
                "https://portswigger.net/web-security/access-control/idor",
            ],
            'ssrf': [
                "https://owasp.org/www-community/attacks/Server_Side_Request_Forgery",
                "https://portswigger.net/web-security/ssrf",
                "https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html",
            ],
        }
        return refs.get(category, ["https://owasp.org/www-project-web-security-testing-guide/"])
    
    def generate_markdown_report(self, filename: str = "vulnerability_report.md"):
        """
        Generate a complete markdown report with all findings
        """
        if not self.reports:
            logger.warning("No reports to generate")
            return
        
        # Sort by severity
        severity_order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3, 'info': 4}
        sorted_reports = sorted(self.reports, key=lambda r: severity_order.get(r.severity, 5))
        
        # Build report
        md = f"""# Security Assessment Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Total Findings:** {len(self.reports)}

## Executive Summary

This security assessment identified **{len(self.reports)}** vulnerabilities:

| Severity | Count |
|----------|-------|
"""
        # Count by severity
        counts = {}
        for r in self.reports:
            counts[r.severity] = counts.get(r.severity, 0) + 1
        
        for sev in ['critical', 'high', 'medium', 'low', 'info']:
            if sev in counts:
                md += f"| {sev.upper()} | {counts[sev]} |\n"
        
        md += """
## Findings Summary

| # | Title | Severity | CVSS | URL |
|---|-------|----------|------|-----|
"""
        for i, r in enumerate(sorted_reports, 1):
            md += f"| {i} | {r.title[:50]} | {r.severity.upper()} | {r.cvss_score} | {r.affected_url[:50]} |\n"
        
        md += "\n---\n\n# Detailed Findings\n\n"
        
        for i, r in enumerate(sorted_reports, 1):
            md += f"## {i}. {r.title}\n\n"
            md += r.to_markdown()
            md += "\n---\n\n"
        
        # Write to file
        output_path = self.output_dir / filename
        with open(output_path, 'w') as f:
            f.write(md)
        
        logger.info(f"Report saved to {output_path}")
        return output_path
    
    def generate_json_report(self, filename: str = "vulnerability_report.json"):
        """Generate JSON report"""
        data = {
            'generated_at': datetime.now().isoformat(),
            'total_findings': len(self.reports),
            'findings': [r.to_dict() for r in self.reports]
        }
        
        output_path = self.output_dir / filename
        with open(output_path, 'w') as f:
            json.dump(data, f, indent=2, default=str)
        
        logger.info(f"JSON report saved to {output_path}")
        return output_path
    
    def generate_all_reports(self, findings: List[Dict], base_filename: str = "vulnhunter_report"):
        """
        Generate all report formats from findings
        
        LLM Usage:
            generator.generate_all_reports(findings, "my_assessment")
        """
        # Create reports from findings
        for finding in findings:
            self.create_report_from_finding(finding)
        
        # Generate reports
        md_path = self.generate_markdown_report(f"{base_filename}.md")
        json_path = self.generate_json_report(f"{base_filename}.json")
        
        return {
            'markdown': str(md_path),
            'json': str(json_path),
            'count': len(self.reports)
        }
